name: rnn-ppo-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - brotli=1.1.0=h2466b09_3
  - brotli-bin=1.1.0=h2466b09_3
  - brotli-python=1.1.0=py310h9e98ed7_3
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2025.6.15=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.6.15=pyhd8ed1ab_0
  - cffi=1.17.1=py310ha8f682b_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - contourpy=1.3.2=py310hc19bc0b_0
  - cuda-cccl=12.9.27=0
  - cuda-cccl_win-64=12.9.27=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - cycler=0.12.1=pyhd8ed1ab_1
  - double-conversion=3.3.1=he0c23c2_0
  - filelock=3.18.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.4=py310h38315fa_0
  - freetype=2.13.3=h57928b3_1
  - graphite2=1.3.14=he0c23c2_0
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.2.1=h8796e6f_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.10=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - kiwisolver=1.4.7=py310hc19bc0b_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.9.0=12_win64_mkl
  - libbrotlicommon=1.1.0=h2466b09_3
  - libbrotlidec=1.1.0=h2466b09_3
  - libbrotlienc=1.1.0=h2466b09_3
  - libcblas=3.9.0=12_win64_mkl
  - libclang13=20.1.7=default_h6e92b77_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.24=h76ddb4d_0
  - libexpat=2.7.0=he0c23c2_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.13.3=h57928b3_1
  - libfreetype6=2.13.3=h0b5ce68_1
  - libgcc=15.1.0=h1383e82_2
  - libglib=2.84.2=hbc94333_0
  - libgomp=15.1.0=h1383e82_2
  - libhwloc=2.11.2=default_ha69328c_1001
  - libiconv=1.18=h135ad9c_1
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - liblapack=3.9.0=12_win64_mkl
  - liblzma=5.8.1=h2466b09_2
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.49=h7a4582a_0
  - libsqlite=3.50.1=h67fdade_0
  - libtiff=4.7.0=h05922d8_5
  - libuv=1.51.0=h2466b09_0
  - libwebp-base=1.5.0=h3b0e114_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.8=h442d1da_0
  - libxslt=1.1.39=h3df6e99_0
  - libzlib=1.3.1=h2466b09_2
  - markupsafe=3.0.2=py310h38315fa_1
  - matplotlib=3.10.3=py310h5588dad_0
  - matplotlib-base=3.10.3=py310h37e0a56_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - numpy=2.2.6=py310h4987827_0
  - opencl-headers=2025.06.13=he0c23c2_0
  - openjpeg=2.5.3=h4d64b90_0
  - openssl=3.5.0=ha4e3fda_1
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.45=h99c9b8b_0
  - pillow=11.2.1=py310h9595edc_0
  - pip=25.1.1=pyh8b19718_0
  - pixman=0.46.2=had0cd8c_0
  - pthread-stubs=0.4=h0e40799_1002
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyside6=6.9.1=py310h2d19612_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.10.18=h8c5b53a_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.10=7_cp310
  - pytorch=2.3.1=py3.10_cuda12.1_cudnn8_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py310h38315fa_2
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.1=h02ddd7d_0
  - requests=2.32.4=pyhd8ed1ab_0
  - scikit-learn=1.7.0=py310hf2a6c47_1
  - scipy=1.15.2=py310h15c175c_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - sympy=1.14.0=pyh04b8f61_5
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h2c6b04d_2
  - tornado=6.5.1=py310ha8f682b_0
  - typing_extensions=4.14.0=pyhe01879c_0
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=16.0.0=py310ha8f682b_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_26
  - vc14_runtime=14.42.34438=hfd919c2_26
  - vs2015_runtime=14.42.34438=h7142326_26
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - yaml=0.2.5=h8ffe710_2
  - zstandard=0.23.0=py310ha8f682b_2
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - absl-py==2.3.0
      - ale-py==0.11.1
      - annotated-types==0.7.0
      - chex==0.1.89
      - click==8.2.1
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - dataclasses-json==0.6.7
      - etils==1.12.2
      - f1tenth-gym==1.0.0.dev0
      - farama-notifications==0.0.4
      - flax==0.10.6
      - fsspec==2025.5.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.73.0
      - gymnasium==0.29.1
      - humanize==4.12.3
      - importlib-resources==6.5.2
      - intel-openmp==2021.4.0
      - jax==0.6.2
      - jaxlib==0.6.2
      - llvmlite==0.44.0
      - lz4==4.4.4
      - markdown==3.8.1
      - markdown-it-py==3.0.0
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - mkl==2021.4.0
      - ml-dtypes==0.5.1
      - msgpack==1.1.1
      - mypy-extensions==1.1.0
      - nest-asyncio==1.6.0
      - numba==0.61.2
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - optax==0.2.5
      - orbax-checkpoint==0.11.16
      - pandas==2.3.0
      - platformdirs==4.3.8
      - protobuf==6.31.1
      - psutil==7.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygame==2.6.1
      - pygments==2.19.1
      - pyopengl==3.1.9
      - pyopengl-accelerate==3.1.9
      - pyqt6==6.9.0
      - pyqt6-qt6==6.9.1
      - pyqt6-sip==13.10.2
      - pyqtgraph==0.13.7
      - pytz==2025.2
      - rich==14.0.0
      - rosbags==0.10.10
      - ruamel-yaml==0.18.14
      - ruamel-yaml-clib==0.2.12
      - sb3-contrib==2.6.0
      - sentry-sdk==2.30.0
      - setproctitle==1.3.6
      - simplejson==3.20.1
      - skrl==1.4.3
      - smmap==5.0.2
      - stable-baselines3==2.6.0
      - tbb==2021.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.75
      - toolz==1.0.0
      - torchaudio==2.3.1
      - torchvision==0.18.1
      - tqdm==4.67.1
      - treescope==0.1.9
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - wandb==0.20.1
      - werkzeug==3.1.3
      - yamldataclassconfig==1.5.0
      - zipp==3.23.0
prefix: C:\Users\jeffe\.conda\envs\rnn-ppo-gpu
